name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build the application
        run: npm run build  # Or `next build` if needed for Next.js

      - name: Start application server
        run: npm start &
        env:
          CI: true

      - name: Wait for the app to be ready
        run: npx wait-on http://localhost:3000  # Ensure the app is ready before running tests

      - name: Run Cypress tests
        run: npx cypress run
