name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js (using version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the application (create production build for Next.js)
      - name: Build the application
        run: npm run build  # Or `next build` if it's a custom command for Next.js

      # Start the application server
      - name: Start application server
        run: npm start &
        env:
          CI: true

      # Wait for the server to be ready (using wait-on to ensure it's accessible)
      - name: Wait for the app to be ready
        run: npx wait-on http://localhost:3000  # Wait until the server is ready

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run
